meta_product_name: "Folly Farm"
meta_title: "Folly Farm - Cotswold Camping."
meta_description: "Folly Farm Cotswold Camping is a quiet site in the heart of the Cotswolds. It is in an “area of outstanding natural beauty” close to the villages of Cold Aston and Notgrove."
meta_image: "http://res.cloudinary.com/di7okux3q/image/upload/v1523797757/pdfkyr0oqeiythbwutye.jpg"
